# Generated by Django 5.1.15 on 2026-05-12 22:19

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models
from django.db.models.functions import Cast


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_add_search_vector_trigger'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name='todo',
            name='search_document',
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    django.db.models.functions.comparison.Coalesce(
                        Cast('title', models.TextField()),
                        models.Value('', output_field=models.TextField()),
                    ),
                    models.Value(' ', output_field=models.TextField()),
                    django.db.models.functions.comparison.Coalesce(
                        Cast('notes', models.TextField()),
                        models.Value('', output_field=models.TextField()),
                    ),
                ),
                output_field=models.TextField(),
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX todos_todo_search_document_trgm_gin
                ON todos_todo USING GIN (search_document gin_trgm_ops);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS todos_todo_search_document_trgm_gin;
            """,
        ),
    ]
